// <auto-generated />
namespace HangmanMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GameBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201702091158005_GameBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
